name: My First GitHub Action

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run message
        run: echo "Hello from GitHub Actions"

      - name: Check files
        run: ls -la
